drive_topic: "/vesc/ackermann_cmd_mux/input/navigation"
velocity: 0.75
desired_distance_front: 0.25
desired_distance_side: 0.18
time_constant: 0.3
num_items_in_avg: 10
num_items_per_side_front: 60
num_items_per_side_side: 40
